# Generated by Django 5.1.3 on 2024-11-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('History', 'History'), ('Geography', 'Geography'), ('English', 'English'), ('General Knowledge', 'General Knowledge')], default='General Knowledge', max_length=50),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
